dotfile '.config/nvim'
dotfile '.config/karabiner'
dotfile '.config/sheldon'
dotfile '.gitconfig'
dotfile '.gitignore'
dotfile '.peco'
dotfile '.tmux.conf'
dotfile '.tmux.conf.local' => '.tmux.conf.darwin'
dotfile '.zsh'
dotfile '.zshrc'
dotfile '.zshrc.darwin'
dotfile '.starship.toml'

package 'git'

include_recipe 'gpg-agent'
