version: 2
jobs:
  debian:
    docker:
      - image: circleci/python:3.6.5
        user: circleci
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            sudo apt-get update -y
            sudo apt-get install -y curl git make zsh tmux
            sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
              libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
              xz-utils tk-dev libffi-dev liblzma-dev python-openssl
      - run:
          name: locale
          command: |
            sudo apt-get update && sudo apt-get install -y locales locales-all
            sudo locale-gen ja_JP.UTF-8
            sudo update-locale
      - run:
          name: test installation
          shell: /usr/bin/zsh
          command: |
            export USER=circleci
            mkdir -p $HOME/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            zsh -c "$(curl -L https://raw.githubusercontent.com/himkt/dotfiles/master/bin/installer.sh)"
      - run:
          name: brew
          shell: /usr/bin/zsh
          command: |
            echo "hello"
workflows:
  version: 2
  build_and_test:
    jobs:
      - debian


