version: 2
jobs:
  debian:
    docker:
      - image: circleci/python:3.6.5
        user: circleci
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            sudo apt-get update -y
            sudo apt-get install -y build-essential wget tmux zsh
      - run:
          name: locale
          command: |
            sudo apt-get update && sudo apt-get install -y locales locales-all
            sudo locale-gen ja_JP.UTF-8
            sudo update-locale
      - run:
          name: configure
          command: |
            mkdir -p $HOME/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: install neovim
          command: |
            cd /tmp
            wget https://github.com/neovim/neovim/releases/download/v0.3.4/nvim-linux64.tar.gz
            tar zxvf nvim-linux64.tar.gz
            sudo mv nvim-linux64/bin/nvim /usr/bin/
      - run:
          name: test installation
          shell: /usr/bin/zsh
          command: |
            make
      - run:
          name: change dir and replace dotfiles
          shell: /usr/bin/zsh
          command: |
            cd $HOME
            mv project .dotfiles
      - run:
          name: build linuxbrew
          shell: /usr/bin/zsh
          command: |
            cd $HOME/.dotfiles
            USER=circleci make build_brew
      - run:
          name: install requirements
          command: |
            cd $HOME/.dotfiles
            echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> ~/.bashrc
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            make brew_bundle
            make requirements
workflows:
  version: 2
  build_and_test:
    jobs:
      - debian


