version: 2
jobs:
  ubuntu1604:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            apt-get update -y && apt-get install -y curl git make zsh ruby
            apt-get install software-properties-common
            apt-get install python-software-properties
            add-apt-repository ppa:neovim-ppa/stable
            apt-get update
            apt-get install neovim
            apt-get install python-dev python-pip python3-dev python3-pip
            pip3 install neovim
      - run:
          name: test on installation
          command: |
            mkdir -p $HOME/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            bash -c "$(curl -L https://raw.githubusercontent.com/himkt/dotfiles/master/bin/installer.sh)"
workflows:
  version: 2
  build_and_test:
    jobs:
      - ubuntu1604
