version: 2
jobs:
  ubuntu1604:
    docker:
      - image: ubuntu:16.04
        user: himkt
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            apt-get update -y && apt-get install -y curl git make zsh ruby language-pack-ja tmux
            apt-get install -y software-properties-common python-software-properties
            add-apt-repository -y ppa:neovim-ppa/stable
            apt-get update -y
            apt-get install -y neovim python-dev python-pip python3-dev python3-pip
            pip3 install neovim
      - run:
          name: test installation
          command: |
            mkdir -p $HOME/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            bash -c "$(curl -L https://raw.githubusercontent.com/himkt/dotfiles/build-automation/bin/installer.sh)"
workflows:
  version: 2
  build_and_test:
    jobs:
      - ubuntu1604
