version: 2
jobs:
  debian:
    docker:
      - image: circleci/buildpack-deps:xenial
        user: circleci
    steps:
      - checkout
      - run:
          name: locale
          command: |
            sudo apt-get update && sudo apt-get install -y locales locales-all
            sudo locale-gen ja_JP.UTF-8
            sudo update-locale
      - run:
          name: configure to connect to github.com
          command: |
            mkdir -p $HOME/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: build linuxbrew
          command: |
            USER=circleci make build_brew
            echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> ~/.bashrc
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            make brew_bundle
          no_output_timeout: 60m
      - run:
          name: test make
          shell: /home/linuxbrew/.linuxbrew/bin/zsh
          command: |
            cd $HOME
            mv project .dotfiles
            cd $HOME/.dotfiles
            make
      - run:
          name: test make requirements
          shell: /home/linuxbrew/.linuxbrew/bin/zsh
          command: |
            cd $HOME/.dotfiles
            make requirements
workflows:
  version: 2
  build_and_test:
    jobs:
      - debian
