version: 2
jobs:
  debian:
    docker:
      - image: circleci/python:3.6.5
        user: circleci
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            sudo apt-get update -y
            sudo apt-get install -y curl git make zsh ruby tmux
            sudo apt-get install -y neovim
            pip install neovim --user
      - run:
          name: test installation
          command: |
            mkdir -p $HOME/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            bash -c "$(curl -L https://raw.githubusercontent.com/himkt/dotfiles/build-automation/bin/installer.sh)"
workflows:
  version: 2
  build_and_test:
    jobs:
      - debian
