shell = "zsh"

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ['source']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['source']

[plugins.zsh-platform-switcher]
github = 'himkt/zsh-platform-switcher'
apply = ['source']
