name: "build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update -y && sudo apt install -y zsh
        if: matrix.os == 'ubuntu-latest'
      - name: setup ${{ matrix.os }}
        run: |
          cp -r $GITHUB_WORKSPACE $HOME/dotfiles
          cd $HOME/dotfiles
          make
          make brew
      - run: |
          make brew-base
          brew doctor
        shell: zsh {0}
