

name: "build"

on: [push]

jobs:
  check_pr:

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build linuxbrew
      run: |
        cp -r $GITHUB_WORKSPACE $HOME/dotfiles && cd $HOME/dotfiles
        make brew
