

name: "build"

on: [push]

jobs:
  check_pr:

    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: setup
        run: |
          cp -r $GITHUB_WORKSPACE $HOME/dotfiles && cd $HOME/dotfiles
          make

      - name: make {brew,brew-optional}
        run: |
          make brew
          make brew-base
          make brew-optional

      - name: zsh
        run: |
          make zsh
          make sheldon
