

name: "build"

on: [push]

jobs:
  check_pr:

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Build linuxbrew
      run: |
        make brew
        eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        make brew_cui
        make
