name: "build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: uninstall builtin homebrew on macOS
        if: matrix.os == 'macos-latest'
        run: |
          sudo rm -rf /opt/homebrew
      - name: setup zsh for ubuntu-latest
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update -y
          sudo apt install -y zsh
          chsh -s $(which zsh)
      - name: setup ${{ matrix.os }}
        run: |
          cp -r $GITHUB_WORKSPACE $HOME/dotfiles
          cd $HOME/dotfiles
          make
          make brew
      - name: install packages
        run: |
          source $HOME/.zshrc
          make brew-base
        shell: zsh {0}
      - name: brew doctor on macOS
        if: matrix.os == 'macos-latest'
        run: |
          # NOTE(himkt); skip this on Ubuntu since brew doctor won't succeed
          #              due to the installation path.
          brew doctor
