name: "build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    strategy:
      matrix:
        os: [macos-latest, ubuntu]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: setup ${{ matrix.os }}
        run: |
          cp -r $GITHUB_WORKSPACE $HOME/dotfiles
          cd $HOME/dotfiles
          make
      - run: |
          which zsh
